pring:
  application:
    name: sports-kpi-tracker
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  flyway:
    enabled: true
    create-schemas: true
    schemas: flyway_history_schema, dbo
    locations: classpath:db/migration

# Server configuration
server:
  port: 8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging configuration
logging:
  level:
    root: INFO
    com.sportskpi: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR

---
# Development environment profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=practice_plan;trustServerCertificate=true
    username: dev_user
    password: P@ssw0rd1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Enable detailed error messages for development
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

---
# Production environment profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: never

# Production server configuration with SSL
server:
  ssl:
    enabled: true
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: practice-plan
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false